name: Apply Severity Label
on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Set label based on severity
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ${{ github.event.issue.body.contains('Critical') && 'Critical' || '' }}
            ${{ github.event.issue.body.contains('High') && 'High' || '' }}
            ${{ github.event.issue.body.contains('Moderate') && 'Moderate' || '' }}
            ${{ github.event.issue.body.contains('Low') && 'Low' || '' }}
